### ISSUE TITLE
Writing to chris.log

### ISSUE THREAD

**Issue by TheRealJAG** [gaugeinteractive/MergeMinify_Magento#2]
In lib/MergeMinify/JS.php I would comment out/remove the following line. Creates an unnecessary log file on the server. 

Line 108
`Mage::log($dataDir, null, 'chris.log', true);`

**Comment by TheRealJAG** [comment]
Created a PR for the change.

**Comment by cproach** [comment]
Thank you. Some of my testing was left in.

**Comment by TheRealJAG** [comment]
Anything else that I should be aware of?

**Comment by TheRealJAG** [comment]
@cproach  I keep running into problems with "Merge JavaScript by Handle". Is there an advantage of enabling?

**Comment by cproach** [comment]
Here is an article that goes into more detail on what I was trying to accomplish.

https://fishpig.co.uk/magento/optimisation/advanced-javascript-merging/
