### ISSUE TITLE
Make JavaScript Asynchronous

### ISSUE THREAD

**Issue by TheRealJAG** [gaugeinteractive/MergeMinify_Magento#4]
Greetings, I was looking at my page speed tests and I'm getting errors for **Make JavaScript Asynchronous**. 

Have you tried doing this yet with this code? I was going to dive into it but I wanted to check first.

**Comment by joeyhoer** [comment]
Scripts may have dependancies. If scripts are loaded asynchronously, their dependancies may not be available when the script executes.

Unfortunately determining which scripts have dependancies and what those dependancies are is not something we're able to automate within this extension.
